# Generated by Django 2.2.3 on 2019-10-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191021_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Institute'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Student'),
        ),
    ]
