# Generated by Django 2.2.3 on 2019-07-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('individual', models.BooleanField(default=True)),
                ('organizationId', models.IntegerField()),
                ('batchId', models.IntegerField()),
                ('mobileNumber', models.CharField(max_length=15)),
                ('verified', models.BooleanField(default=False)),
                ('verifiedTime', models.DateTimeField()),
                ('expiryDate', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.IntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentId', to='webapp.Student')),
            ],
        ),
    ]
