# Generated by Django 2.2.3 on 2019-10-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('verifiedTime', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('studentCap', models.IntegerField()),
                ('mobileNumber', models.CharField(max_length=15)),
                ('alternateNumber', models.CharField(max_length=15)),
                ('expiryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('rollNumber', models.CharField(max_length=100, null=True)),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('individual', models.BooleanField(default=True)),
                ('batchId', models.IntegerField()),
                ('mobileNumber', models.CharField(max_length=15)),
                ('verified', models.BooleanField(default=False)),
                ('verifiedTime', models.DateTimeField(null=True)),
                ('expiryDate', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Institute')),
            ],
        ),
    ]
