# Generated by Django 2.2.3 on 2019-09-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190912_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='userId',
            new_name='user',
        ),
    ]
